[enigma2.sh] Fix path and detected bootlog after restart enigma2
OpenVisionE2/enigma2-openvision pull request #245
Opened 2021-06-11 17:37 UTC by fairbird

-Shorten the code, add the missing default path, and correction the recognition of the correct path for the bot logo.
-@sysconfdir@, @prefix@ and @bindir@ doesn't work correctly (broken right path).
-Quotation marks (") also no need it with $?? does not work smoothly with this enigma2.sh script file.

2021-06-11 18:19 UTC, persianpros commented
Just a quick look:

This is wrong, OE manages the path loactions correctly and I didn't see any problem with that.

The part shortens the code is wrong also I think because we should use exteplayer3 only if it exists otherwise use showiframe which is always available.

So no need to check for showiframe as it's always available and we should not use "and/or" because exteplayer3 is optional and when it's not there we should never run bootlogo.mp4 so only one check is required which is exteplayer3 and then run bootlogo.mp4 otherwise always .mvi

2021-06-11 18:41 UTC, fairbird commented
1-This is wrong way to focus only with (exteplayer3) and make it the video bootlogo the main bootlog ... not ala user like it !
2-I was test the original code more than 5 times after I get feedback from a lot of friends and does not work correctly ... try to restart GUI you will never see the bootlogo after restart GUI because I as mentioned @sysconfdir@, @Prefix@ and @bindir@ doesn't work correctly (broken right path). And also Quotation marks (").
3-About to check showiframe it is important with this code
> if [ -x "/usr/bin/exteplayer3" -o -x "/usr/bin/showiframe" ]; then
If missing exteplayer3 from image the code will be not working and no need to use long code like this
> if [ -x "@bindir@/exteplayer3" ]; then
		for DIR in "$SEARCHDIRS"
		do
			if [ -d "${DIR}" ] && [ -f "${DIR}/bootlogo.mp4" ]; then
				"@bindir@/exteplayer3" "${DIR}/bootlogo.mp4"
				break
			fi
		done
	else
		if [ -x "@bindir@/showiframe" ]; then
			for DIR in "${SEARCHDIRS}"
			do
				if [ -d "${DIR}" ] && [ -f "${DIR}/bootlogo.mvi" ]; then
					if [ "${SOCFAMILY}" == "hisi" ]; then
						killall -9 showiframe; sleep 1
					fi
					"@bindir@/showiframe" "${DIR}/bootlogo.mvi"
					break
				fi
			done
		fi
fi
4-It is ok for me no problem I can create personal patch to use it with build ... If you did not agree  the pull request you can close it.

2021-06-11 19:40 UTC, persianpros commented
I need to test it and see the difference

2021-06-12 04:32 UTC, IanSav commented
While I would also like to see the removal of the path obfuscation this would be against the design and coding standards of Enigma2.  If any of these paths were to be changed in the build system then this script could/would become out of step with the rest of Enigma2.

The "/usr/share" directory has been deliberately removed as it encourages clutter of the file system with Enigma2 only related files.  The boot logos are part of the Enigma2 visual / UI system and should, as such, be kept with the other Enigma2 visual / UI system components.

I have previously had issues where "showiframe" has *not* been available.  For OpenVision I was told it will always be available to I relaxed the availability test.  You should never assume that *any* package is installed by default.  I am more than happy to see the availability test returned.

I have no objection to compressing the image and movie search loops into one.  There should be no perceivable performance issues.

2021-06-12 04:36 UTC, IanSav commented on tools/enigma2.sh.in
> +	SKIN=`sed -En 's|^config\.skin\.primary_skin=(.+)/skin\.xml$|\1|p' "/etc/enigma2/settings"`
This may cause issues if any of the Enigma2 build system paths are changed.

2021-06-12 04:37 UTC, IanSav commented on tools/enigma2.sh.in
> +		SKIN=`strings -n 10 "/usr/lib/enigma2/python/skin.pyo" | egrep -o -m 1 ".+/skin.xml" | sed 's|/skin.xml.*||'`
See above.

2021-06-12 04:37 UTC, IanSav commented on tools/enigma2.sh.in
> +		SEARCHDIRS="/etc/enigma2/$skin /etc/enigma2/skin_common /etc/enigma2 /usr/share/enigma2/$skin /usr/share/enigma2/skin_default /usr/share/enigma2 /usr/share"
And again.

2021-06-12 04:38 UTC, IanSav commented on tools/enigma2.sh.in
> +		SEARCHDIRS="/etc/enigma2/skin_common /etc/enigma2 /usr/share/enigma2/skin_default /usr/share/enigma2 /usr/share"
See previous comment.

2021-06-12 04:39 UTC, IanSav commented on tools/enigma2.sh.in
> +		for DIR in $SEARCHDIRS
This is fine.

2021-06-12 04:39 UTC, IanSav commented on tools/enigma2.sh.in
> +				"/usr/bin/showiframe" "${DIR}/bootlogo.mvi"
This is fine.

2021-06-12 04:40 UTC, IanSav commented on tools/enigma2.sh.in
> -		fi
It is fine to combine this loop with the one above.

2021-06-12 04:41 UTC, IanSav requested changes
While I would also like to see the removal of the path obfuscation this would be against the design and coding standards of Enigma2.  If any of these paths were to be changed in the build system then this script could/would become out of step with the rest of Enigma2.

The "/usr/share" directory has been deliberately removed as it encourages clutter of the file system with Enigma2 only related files.  The boot logos are part of the Enigma2 visual / UI system and should, as such, be kept with the other Enigma2 visual / UI system components.  These boot logo images have been permanently moved to "/usr/share/enigma2/".

I have previously had issues where "showiframe" has *not* been available.  For OpenVision I was told it will always be available to I relaxed the availability test.  You should never assume that *any* package is installed by default.  I am more than happy to see the availability test returned.

I have no objection to compressing the image and movie search loops into one.  There should be no perceivable performance issues.

2021-06-13 01:24 UTC, IanSav requested changes
I have marked the changes that are okay as resolved.

I believe that the removal of the build parameters is still problematic.

2021-06-14 10:25 UTC, persianpros commented
This is how .sh looks for h9 with today build:

[enigma2.zip](https://github.com/OpenVisionE2/enigma2-openvision/files/6647602/enigma2.zip)

So path is ok, please send a new PR only with the part shortens the code and please allow editing on your PRs so I could do the needed edits instead of having a new PR :+1:

2021-06-14 10:25 UTC, closed without merging